# Generated by Django 3.2.12 on 2023-04-19 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.CharField(max_length=64)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.lista')),
            ],
        ),
    ]
